<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sql\**\*.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="installer\**\*.cs" />
    <Content Remove="installer\**\*" />
    <None Remove="installer\**\*" />
  </ItemGroup>

</Project>
